### ISSUE TITLE
https is showing near the appyter icon on the google landing page (see screenshot)

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#149]
![image](https://user-images.githubusercontent.com/12749033/86851042-42f63500-c080-11ea-8acb-415ac9c67d98.png)

**Comment by u8sand** [comment]
This is likely because we don't currently have a `<title>` set, I'll set it along with the `meta` tags so that we get image, description, links, tags, etc.. with google.

**Comment by AviMaayan** [comment]
👍
