### ISSUE TITLE
Short name on Google shortcuts shows https instead of Appyters

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#410]
![image](https://user-images.githubusercontent.com/12749033/90094398-d5cb6480-dcfb-11ea-9924-8e418dbe37db.png)

**Comment by u8sand** [comment]
![image](https://user-images.githubusercontent.com/1341861/90141533-3df46780-dd49-11ea-8a2e-f4241ae094dc.png)

I'm pretty sure yours is cached somehow..
