### ISSUE TITLE
Remove e-mails from the appyter introduction page near author names

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#481]
We do not want users contacting authors directly for help. Users should be directed to GitHub if they need help. This way we can monitor user needs and keep proper response for support.

**Comment by u8sand** [comment]
Fixed in https://github.com/MaayanLab/appyter-catalog/commit/2d39e5a0ce2681a3d7b14940a4eb7beb30ef2e38
