### ISSUE TITLE
Resize appyter logo on pages that have appyters executing

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#482]
The size of the logo appears bigger on the appyter execution pages. It should be made smaller and match the size of it on the catalog landing page.

**Comment by u8sand** [comment]
This has to do with style interference and part of the reason I'm still moving everything to svelte which isolates styles. Unfortunately neither the jupyter styles nor the override mechanism are in svelte so I need to remove the interfering styles from the appyter library itself.

**Comment by u8sand** [comment]
Fixed via https://github.com/MaayanLab/appyter/commit/837d43d4a6649aa776a1f63eb3a86ac7a8e45a79 and https://github.com/MaayanLab/appyter/commit/837d43d4a6649aa776a1f63eb3a86ac7a8e45a79
