### ISSUE TITLE
Footer still links to old documentation please remove this entry or link Creating and Publishing pages

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#545]
Also, please remove the link to the paper from the footer... It is good the way we have it now in the About page but it does not look right in the footer.

**Comment by u8sand** [comment]
Fixed in 3ed20f9e28d8d5c1633d7b88ae731f30a87cc58c & 0d09551ca36165bf508acc464865e2e35b0f7a50
