### ISSUE TITLE
[DrugShot]: Improve formatting of left menu & table titles in DrugShot Appyters notebooks

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/appyter-catalog#549]
Two issues related to aesthetics of the DrugShot Appyters notebooks (see screenshots below):

(a) The left menu's text looks messy and could be neatened in format.

(b) Some of the hyperlinked table titles have text that overlap the preceding line of text, and the titles are so long that their right side is cut off. This could be fixed by increasing the spacing between these lines, and reducing the hyperlinked text's font size.

I have reproduced this issue across several browsers (Chrome, Firefox, Microsoft Edge) on a Windows 10 machine, so the behavior is not browser-specific.

![DrugShot_LeftMenu_UnattractiveAppearance_v1_3-13-21](https://user-images.githubusercontent.com/7283504/111057755-dfff3e00-8457-11eb-98aa-2ed4841fbc46.PNG)

![DrugShot_Table2_Title_UnattractiveFormatting_v1_3-13-21](https://user-images.githubusercontent.com/7283504/111057763-e988a600-8457-11eb-9ea3-cc3bcd99fb56.PNG)

![DrugShot_Table3_Title_UnattractiveFormatting_v1_3-13-21](https://user-images.githubusercontent.com/7283504/111057768-ef7e8700-8457-11eb-83fa-b42a388e4da7.PNG)

**Comment by u8sand** [comment]
We did improve sizing of the table of contents in the appyter library, hopefully addressing this
