### ISSUE TITLE
[DrugShot]: Appyter doesn't display or function correctly using Safari browser

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/appyter-catalog#550]
I've tested the DrugShot site/Appyter using Chrome, Firefox, and Microsoft Edge on both a Windows 10 machine and on Mac OS X Yosemite 10.10.2, and it displays & functions fine using those browsers. In contrast, when I test it using the Safari browser (Version 8.0.3 (10600.3.18)), the input parameter menus are missing, and the orientation of the elements on the homepage are different than as displayed in other browsers (e.g. the Appyter-related menu items are displayed at the top right of the homepage using the functional browsers, but these menu items are in the left-center of the homepage using Safari). See screenshot for an illustration of these issues.

![image](https://user-images.githubusercontent.com/7283504/111058024-9ca5cf00-8459-11eb-841f-e5b95c0791c6.png)

**Comment by u8sand** [comment]
@KMJ1618 I do not have access to a Safari browser to debug this. Can you please send me any errors in the Inspect console?

**Comment by u8sand** [comment]
Closing this stale issue. The HTML itself seems fine and I cannot reproduce it; perhaps it has since been fixed.
