### ISSUE TITLE
Links to Enrichr in Enrichment_Analysis_Visualizer Appyter seem to be broken

### ISSUE THREAD

**Issue by ekropiwnicki** [MaayanLab/appyter-catalog#551]
Clicking the Enrichr link at the bottom of this notebook brings the user to an expired page. I believe this will be the same for all notebooks output by this Appyter.

https://appyters.maayanlab.cloud/Enrichment_Analysis_Visualizer/cf80c214752fa47327f231ec705d736f753b7d60/

**Comment by u8sand** [comment]
Oh dear, this seems to be an issue with the proxy effecting any amp.pharm link.. i'll get on it right away..

Specifically
https://amp.pharm.mssm.edu/Enrichr/enrich?dataset=f8e635f0c40dd80288f950f1b190685c

is not going to 
https://maayanlab.cloud/Enrichr/enrich?dataset=f8e635f0c40dd80288f950f1b190685c

Instead it's going to
https://maayanlab.cloud/Enrichr/enrich

**Comment by u8sand** [comment]
Fixed in https://github.com/MaayanLab/proxy/commit/08dae45ee98b1319d8f9f466aa060abbf91b4a75
