### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by jic40** [MaayanLab/appyter-catalog#774]
If I try to click Appyter, it show errors as th showing:
TypeError: Cannot read properties of undefined (reading 'location')

**Comment by u8sand** [comment]
@jic40 Thank you for your report, we have recently made a big upgrade to appyters and are still hammering out issues, sorry for any inconvenience.

It would be great to have a bit more information including where precisely you experienced this. Was it from the main catalog? or when submitting an appyter for execution? It might also help to know what browser you are using.

**Comment by u8sand** [comment]
Since we haven't heard back about this, I believe it's likely solved. Please let us know if this is not the case.
