### ISSUE TITLE
Not running. Says "Collision in update" 

### ISSUE THREAD

**Issue by kasumaz** [MaayanLab/appyter-catalog#777]
I would be keen to try out and eventually adapt the code for use elsewhere. 
Cheers.

**Comment by u8sand** [comment]
@kasumaz Thank you for your report. It seems the comparesets appyter and scrna_seq have experienced this. We will look into it.

**Comment by u8sand** [comment]
@kasumaz Thanks again for the report, these two appyters should be fixed and the fix will be rolled out to any other appyters with time. Definitely let us know if you're experiencing any more issues.

**Comment by kasumaz** [comment]
Hi, I checked it out again and I have it working now. Many thanks. 
Something else I wanted to ask...
I am also wondering if the Ma'yaan lab plan to adopt machine learning to associate the LINCs drug data with multiple 'omics' datasets once merged. I have mostly scRNA seq data , bulk RNAse and GWAS data to then go into look for drugs 'corrected' against a few omics platforms.  This is something I am trying to work around. Just incase there is something from the lab in the pipeline. 
Thanks.

**Comment by kasumaz** [comment]
Thanks. I saw this one. I think my comment was too vague. I can only try to implement something myself using some of the code/tools for appyter (which I find very nice).
