### ISSUE TITLE
[Independent_Enrichment_Analysis]: FileNotFoundError for a library from Enrichr

### ISSUE THREAD

**Issue by jlang-prog** [MaayanLab/appyter-catalog#790]
Hello,

I'm using the Independent Enrichment Analysis tool (https://appyters.maayanlab.cloud/Independent_Enrichment_Analysis/) to run Gene Ontology Biological Process enrichment analysis on my gene list of interest with a custom background. However, I keep receiving the error below. Not sure if this indicates that no hits were found or there was an error in the code. I used this tool with other gene lists of interest and a custom background which worked fine. Also, the latest versions for some of these tools are not available. For example, the latest GO BP version is 2018, will an updated version be available, as well as for KEGG? Thanks 

FileNotFoundError                         Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 library_data, items = load(library_filename, items, background_items)
      2 results, pvals, results_df = enrichment_analysis(items, library_data)
      3 if 'p value' in results_df.columns:

Input In [7], in load(library_filename, items, background_items)
      2 if library_kind == "Select a library from Enrichr":
      3     download_library(library_filename)
----> 4 library_data, average_items_in_library = load_library(library_filename, background_items)
      5 # to upper case
      6 items = [x.upper() for x in items]

Input In [7], in load_library(library_filename, background_items)
     17 library_data = dict()
     18 items_in_library = list()
---> 19 with open(library_filename, "r") as f:
     20     lines = f.readlines()
     21     for line in lines:

FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by u8sand** [comment]
The only way I was able to reproduce this is by leaving "Submit your Library" section blank.
![image](https://user-images.githubusercontent.com/1341861/172465718-b0483bd9-27ab-46f5-862f-a766aece46e4.png)

If instead I provide one, I get results on the example set:
![image](https://user-images.githubusercontent.com/1341861/172465904-013bcd7d-0b85-4d03-9dbd-b2659127c7da.png)

https://appyters.maayanlab.cloud/Independent_Enrichment_Analysis/7e81ebade5fdf4d50242153f50d15b23b7c939a2/

Is it possible for your to share the url to the broken input?

**Comment by jordlang1992** [comment]
Actually, I just ran the analysis with the gene list I was having a difficult time obtaining results for and it worked without any error interruptions, very odd. However, my other question still stands, if there are more current versions of GO_Biological Process (2018), KEGG (2016) and REACTOME (2016) available?

**Comment by AviMaayan** [comment]
Hi @jlang-prog yes. There are some updated libraries that you can find here: https://maayanlab.cloud/Enrichr/#libraries

**Comment by jlang-prog** [comment]
Hi @AviMaayan, thank you for letting me know. After the analysis runs, are the p values in the bar plots adjusted or unadjusted?

**Comment by AviMaayan** [comment]
Unadjusted. The adjusted values are in the table...
