### ISSUE TITLE
[CompareSets]: Set Comparison Appyter links to Enrichr

### ISSUE THREAD

**Issue by andreacmeyer** [MaayanLab/appyter-catalog#802]
I am new to coding and I needed to start my analysis by identifying the genes in the 3 datasets that overlap. I used your awesome "Set Comparison Appyter" code and the results are great. I'm just having a difficult time clicking on the links to Enrichr to view the entire set of genes that overlap. I'm speaking specifically of the Table 1: List of Set Intersections, I'd like to be able to download the list of genes, but I can only seems to save them as an image. What am I doing wrong?

Sincerely, Andrea Meyer

**Comment by u8sand** [comment]
@andreacmeyer We're glad you were able to find use of the Set Comparison Appyter. Unfortunately this appyter has some issues which we've not had a chance to address.

We'll look into the issue of the enrichr results link being pretty difficult to access (even though you can see them, you can't click or select them).
