### ISSUE TITLE
Compare Sets Appyter crushes when attempting to processed the attached file

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#883]
[nfat-gmt.txt](https://github.com/MaayanLab/appyter-catalog/files/10953063/nfat-gmt.txt)

**Comment by AviMaayan** [comment]
[nfat-gmt.txt](https://github.com/MaayanLab/appyter-catalog/files/10953067/nfat-gmt.txt)

**Comment by u8sand** [comment]
Duplicate of #719 -- appyter currently supports at most 6 sets

**Comment by u8sand** [comment]
Additionally, the attached GMT looks like it may be malformed. The "first" gene might get lost if they're in the "description" field. Otherwise, if it's indeed a description then it'll be fine.
