### ISSUE TITLE
Enrichr Appyter

### ISSUE THREAD

**Issue by asabulski** [MaayanLab/appyter-catalog#891]
Good morning, 
Appyter has been displaying "Queued successfully, you are at position 1, your execution will begin when resources are available" for several hours and is not generating any figures. Thank you!

**Comment by u8sand** [comment]
Hi @asabulski thank you for letting us know, it seems the queue was stuck on something. it should be addressed now

**Comment by asabulski** [comment]
Thank you, really appreciate it! Working fine now, have a great day!
